name: raftsurvivalui
main: kalsel1295\raftsurvivalui\Main
api: 3.0.0
version: 1.0.0
description: raft survival command but type ui

commands:
  raftui:
    description: "-"
    permission: raft.ui

permissions:
  raft.ui:
    description: "-"
    default: op
